CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -Iinclude -MMD -MP -g

SRC = Seracc.cpp $(wildcard src/*.cpp)
OBJ = $(patsubst %.cpp, build/%.o, $(SRC))
DEP = $(OBJ:.o=.d)

TARGET = Seracc

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET)

build/%.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Pull in header dependencies generated by -MMD
-include $(DEP)

clean:
	rm -rf build $(TARGET)

.PHONY: all clean