// CEmitter.cpp

#include "CEmitter.hpp"

#include <sstream>
#include <iostream>

CEmitter::CEmitter() {}

void CEmitter::emit_c(std::ostream& out,
                      const Program& p,
                      const NamespaceSymbol* /*global_ns*/,
                      const std::vector<ConstructedType>& constructed_types)
{
    current_prog = &p;
    types = &constructed_types;
    ns_stack.clear();

    emit_preamble(out);
    emit_decl_list(out, p.decls);

    current_prog = nullptr;
    types = nullptr;
}

void CEmitter::emit_preamble(std::ostream& out)
{
    out << "/* Generated by Serac compiler (MVP). Source: "
        << (current_prog ? current_prog->file_path : "<unknown>") << " */\n\n";

    out << "#include <stdint.h>\n";
    out << "#include <stdbool.h>\n";
    out << "#include <stddef.h>\n";
    out << "\n";
}

void CEmitter::emit_decl_list(std::ostream& out,
                              const std::vector<std::unique_ptr<Decl>>& decls)
{
    // Pass 1: emit type declarations first (struct/component layouts)
    // so function prototypes can reference them.
    for (const auto& d : decls)
    {
        if (auto ns = dynamic_cast<const NamespaceDecl*>(d.get()))
        {
            emit_namespace(out, ns);
        }
        else if (auto st = dynamic_cast<const StructDecl*>(d.get()))
        {
            emit_struct(out, st);
        }
        else if (auto cp = dynamic_cast<const ComponentDecl*>(d.get()))
        {
            emit_component(out, cp);
        }
    }

    // Pass 2: emit free functions (top-level) after types
    for (const auto& d : decls)
    {
        if (auto fn = dynamic_cast<const FunctionDecl*>(d.get()))
        {
            emit_function(out, fn, /*enclosing_component=*/nullptr);
        }
        // namespaces already handled recursively in emit_namespace()
    }
}

void CEmitter::emit_namespace(std::ostream& out, const NamespaceDecl* ns)
{
    ns_stack.push_back(ns->name);

    // Emit contained decls in two-phase style:
    emit_decl_list(out, ns->decls);

    ns_stack.pop_back();
}

void CEmitter::emit_struct(std::ostream& out, const StructDecl* st)
{
    // In MVP: structs are plain C structs.
    // Use mangled name so namespaces don't collide in C.
    std::string c_name = mangle_name(st->name);

    out << "typedef struct " << c_name << "\n{\n";
    for (const auto& f : st->fields)
    {
        // Field mutability is NOT represented in C types; enforce in Serac later.
        out << "    " << c_type_from_typeref(f.t) << " " << f.name << ";\n";
    }
    out << "} " << c_name << ";\n\n";
}

void CEmitter::emit_component(std::ostream& out, const ComponentDecl* cp)
{
    // Components are also C structs for layout.
    std::string c_name = mangle_name(cp->name);

    out << "typedef struct " << c_name << "\n{\n";
    for (const auto& f : cp->fields)
    {
        out << "    " << c_type_from_typeref(f.t) << " " << f.name << ";\n";
    }
    out << "} " << c_name << ";\n\n";

    // Emit nested containers (types inside component) in the *same namespace prefix*.
    // (You may later want to include the component name in mangling for nested types;
    // for MVP we just treat them as normal types inside the namespace.)
    for (const auto& nc : cp->nested_cnts)
    {
        if (auto st = dynamic_cast<const StructDecl*>(nc.decl.get()))
        {
            emit_struct(out, st);
        }
        else if (auto sub = dynamic_cast<const ComponentDecl*>(nc.decl.get()))
        {
            emit_component(out, sub);
        }
    }

    // Emit component functions (receiver functions)
    for (const auto& fn : cp->functions)
    {
        emit_function(out, fn.get(), cp);
    }
}

void CEmitter::emit_function(std::ostream& out,
                             const FunctionDecl* fn,
                             const ComponentDecl* enclosing_component)
{
    // Name:
    // - top-level function: namespace_mangle(fn->name)
    // - component receiver: namespace_mangle(Component__method)
    std::string c_name;
    if (enclosing_component && fn->receiver_meta.has_value())
        c_name = mangle_method(enclosing_component, fn);
    else
        c_name = mangle_name(fn->name);

    // Return type
    std::string ret_ty = c_type_from_typeref(fn->return_type);

    out << ret_ty << " " << c_name << "(";

    bool first = true;

    // Receiver becomes explicit first parameter.
    if (enclosing_component && fn->receiver_meta.has_value())
    {
        // receiver is always ref/ref mut in your language → pointer in C
        std::string recv_c_ty = c_type_from_typeref(fn->receiver_meta->receiver_type);
        out << recv_c_ty << " " << fn->receiver_meta->receiver_name;
        first = false;
    }

    // Params (you currently don't parse them; code supports when you add them)
    for (const auto& p : fn->parameters)
    {
        if (!first) out << ", ";
        out << c_type_from_typeref(p.t) << " " << p.name;
        first = false;
    }

    if (first)
    {
        out << "void";
    }

    out << ")\n{\n";

    // MVP stub body: you can later splice in translated statements.
    out << "    /* MVP: function body not lowered yet. */\n";

    // Return stub if needed:
    // We can emit something safe-ish for common cases.
    // (You may choose to error if non-void body is missing.)
    const auto& rt = (*types)[fn->return_type.resolved_type_id];
    bool is_void = (rt.base_kind == ConstructedType::BaseKind::BUILTIN &&
                    rt.builtin_name == "void" &&
                    rt.ref_type == ReferenceType::NONE &&
                    rt.ptr_pointee_mut.empty());

    if (!is_void)
    {
        out << "    return (" << ret_ty << ")0;\n";
    }

    out << "}\n\n";
}

// ---------------- Type lowering ----------------

std::string CEmitter::c_type_from_typeref(const TypeRef& tr) const
{
    return c_type_from_typeid(tr.resolved_type_id);
}

std::string CEmitter::c_type_from_typeid(uint64_t type_id) const
{
    if (!types || type_id == 0 || type_id >= types->size())
    {
        // 0 is "<invalid>" in the resolver design I gave you.
        return "/*invalid_type*/ void";
    }

    const ConstructedType& t = (*types)[type_id];

    // Base:
    std::string base;
    if (t.base_kind == ConstructedType::BaseKind::BUILTIN)
    {
        base = builtin_to_c(t.builtin_name);
    }
    else
    {
        // user type: emit as the mangled C struct name
        // NOTE: t.user_sym points to TypeSymbol, whose decl_ptr has the source name.
        base = mangle_name(t.user_sym->decl_ptr->name);
    }

    // References lower to pointers (C has no refs)
    // Also pointer chain: each layer adds '*'.
    // Mut qualifiers not represented in C; enforced in Serac semantics.
    std::ostringstream oss;
    oss << base;

    // In Serac, ref adds a single pointer indirection at the use-site.
    if (t.ref_type != ReferenceType::NONE)
    {
        oss << "*";
    }

    // Each pointer layer adds a '*'
    for (size_t i = 0; i < t.ptr_pointee_mut.size(); ++i)
    {
        oss << "*";
    }

    return oss.str();
}

std::string CEmitter::builtin_to_c(const std::string& b) const
{
    // b is already normalized in resolver (e.g. "i32", "u64")
    if (b == "i8") return "int8_t";
    if (b == "u8") return "uint8_t";
    if (b == "i16") return "int16_t";
    if (b == "u16") return "uint16_t";
    if (b == "i32") return "int32_t";
    if (b == "u32") return "uint32_t";
    if (b == "i64") return "int64_t";
    if (b == "u64") return "uint64_t";

    if (b == "bool") return "bool";
    if (b == "float") return "float";
    if (b == "double") return "double";

    if (b == "void") return "void";
    if (b == "opaque") return "void";

    // fallback
    return "/*unknown_builtin*/ void";
}

// ---------------- Name mangling ----------------

std::string CEmitter::mangle_name(const std::string& base) const
{
    // Namespace prefix: A::B::name  -> A__B__name
    std::ostringstream oss;
    for (size_t i = 0; i < ns_stack.size(); ++i)
    {
        oss << ns_stack[i] << "__";
    }
    oss << base;
    return oss.str();
}

std::string CEmitter::mangle_qualified(const std::string& qualified) const
{
    // If you ever need to mangle a fully-qualified string like "A::B::T"
    // into "A__B__T".
    std::ostringstream oss;
    for (size_t i = 0; i < qualified.size();)
    {
        if (i + 1 < qualified.size() && qualified[i] == ':' && qualified[i + 1] == ':')
        {
            oss << "__";
            i += 2;
        }
        else
        {
            oss << qualified[i++];
        }
    }
    return oss.str();
}

std::string CEmitter::mangle_method(const ComponentDecl* cp,
                                   const FunctionDecl* fn) const
{
    // Method naming convention:
    // <ns_prefix><ComponentName>__<MethodName>
    // e.g. Serac::DynamicArray.add -> Serac__DynamicArray__add
    std::ostringstream oss;
    for (size_t i = 0; i < ns_stack.size(); ++i)
    {
        oss << ns_stack[i] << "__";
    }
    oss << cp->name << "__" << fn->name;
    return oss.str();
}